version: '3.3'

services:
  rabbitmq:
    container_name: rabbitmq
    hostname: rabbitmq
    build:
      context: ./RabbitMQ/
      dockerfile: Dockerfile
    image: rabbitmq:latest
    expose:
      - 5672
      - 15672
    networks:
      - foodhaven

  db:
    image: mysql:8.0
    container_name: db
    ports:
      - 3306:3306
    networks:
      - foodhaven
    volumes:
      - ./databases-dump.sql:/docker-entrypoint-initdb.d/databases-dump.sql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: userServiceDB
      MYSQL_USER: springuser
      MYSQL_PASSWORD: ThePassword

  configuration-service:
    container_name: configuration-service
    hostname: config-service
    build:
      context: ./configuration-service/
      dockerfile: Dockerfile
    image: configuration-service:latest
    restart: always
    environment:
      - FOODHAVEN_GIT_USERNAME=aalialzaya1
      - FOODHAVEN_GIT_PASSWORD=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
    ports:
      - 8888:8888
    networks:
      - foodhaven

  eureka-service:
    container_name: eureka-service
    hostname: discovery-server
    build:
      context: ./eureka-server/
      dockerfile: Dockerfile
    image: eureka-service:latest
    restart: always
    environment:
      - EUREKA_SERVER_URL=http://discovery-server:8761/eureka/
      - HOSTNAME=discovery-server
    ports:
      - 8761:8761
    networks:
      - foodhaven

  system-events-service:
    container_name: system-events-service
    build:
      context: ./system-events-service/
      dockerfile: Dockerfile
    image: system-events-service:latest
    restart: always
    environment:
      - CONFIG_SERVER_URL=http://config-service:8888
      - EUREKA_SERVER_URL=http://discovery-server:8761/eureka/
      - SS_DATABASE_URL=jdbc:mysql://db:3306/systemEventsServiceDB
    ports:
      - 8086:8086
    depends_on:
      - configuration-service
      - eureka-service
      - db
    networks:
      - foodhaven

  user-service:
    container_name: user-service
    build:
      context: ./user-service/
      dockerfile: Dockerfile
    image: user-service:latest
    restart: always
    environment:
      - CONFIG_SERVER_URL=http://config-service:8888
      - EUREKA_SERVER_URL=http://discovery-server:8761/eureka/
      - US_DATABASE_URL=jdbc:mysql://db:3306/userServiceDB
    ports:
      - 8083:8083
    networks:
      - foodhaven
    depends_on:
      - configuration-service
      - eureka-service
      - db

  recipe-service:
    container_name: recipe-service
    build:
      context: ./recipe-service/
      dockerfile: Dockerfile
    image: recipe-service:latest
    restart: always
    environment:
      - CONFIG_SERVER_URL=http://config-service:8888
      - EUREKA_SERVER_URL=http://discovery-server:8761/eureka/
      - RS_DATABASE_URL=jdbc:mysql://db:3306/recipeServiceDB
      - RABBITMQ_HOST=rabbitmq,
    ports:
      - 8082:8082
    networks:
      - foodhaven
    depends_on:
      - rabbitmq
      - configuration-service
      - eureka-service
      - db

  rating-service:
    container_name: rating-service
    build:
      context: ./rating-service/
      dockerfile: Dockerfile
    image: rating-service:latest
    restart: always
    environment:
      - CONFIG_SERVER_URL=http://config-service:8888
      - EUREKA_SERVER_URL=http://discovery-server:8761/eureka/
      - RRS_DATABASE_URL=jdbc:mysql://db:3306/reviewServiceDB
      - RABBITMQ_HOST=rabbitmq
    ports:
      - 8081:8081
    networks:
      - foodhaven
    depends_on:
      - rabbitmq
      - configuration-service
      - eureka-service
      - db

  ingredient-service:
    container_name: ingredient-service
    build:
      context: ./ingredient-service/
      dockerfile: Dockerfile
    image: ingredient-service:latest
    restart: always
    environment:
      - CONFIG_SERVER_URL=http://config-service:8888
      - EUREKA_SERVER_URL=http://discovery-server:8761/eureka/
      - IS_DATABASE_URL=jdbc:mysql://db:3306/ingredientServiceDB
    ports:
      - 8084:8084
    networks:
      - foodhaven
    depends_on:
      - configuration-service
      - eureka-service
      - db

  api-gateway:
    container_name: api-gateway
    hostname: api-gateway
    build:
      context: ./api-gateway/
      dockerfile: Dockerfile
    image: api-gateway:latest
    restart: always
    environment:
      - EUREKA_SERVER_URL=http://discovery-server:8761/eureka/
    ports:
      - 8088:8088
    depends_on:
      - rabbitmq
      - db
      - configuration-service
      - eureka-service
      - system-events-service
      - user-service
      - recipe-service
      - rating-service
      - ingredient-service
    networks:
      - foodhaven

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: frontend:latest
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - api-gateway
    networks:
      - foodhaven

networks:
  foodhaven:
    driver: bridge