version: '3'

services:
  rabbitmq:
    container_name: rabbitmq
    hostname: rabbitmq
    build:
      context: ./RabbitMQ
    image: docker-rabbitmq
    expose:
      - 5672
      - 15672
    networks:
      - foodhaven

  db:
    image: mysql:8.0
    container_name: db
    expose:
      - 3306
    networks:
      - foodhaven
    volumes:
      - ./databases.sql:/docker-entrypoint-initdb.d/databases.sql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: springuser
      MYSQL_PASSWORD: ThePassword

  configuration-service:
    container_name: config-service
    hostname: config-service
    build:
      context: ./configuration-service
    image: docker-configuration-service
    environment:
      - JAVA_TOOL_OPTIONS=-XX:+TieredCompilation -XX:TieredStopAtLevel=1 -Xss256k
      - FOODHAVEN_GIT_USERNAME=aalialzaya1
      - FOODHAVEN_GIT_PASSWORD=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
    expose:
      - 8888
    networks:
      - foodhaven
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 5

  eureka-service:
    container_name: eureka
    hostname: discovery-server
    build:
      context: ./eureka-server
    image: docker-eureka
    environment:
      - JAVA_TOOL_OPTIONS=-XX:+TieredCompilation -XX:TieredStopAtLevel=1 -Xss256k
    expose:
      - 8761
    networks:
      - foodhaven
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 5

  system-events-service:
    container_name: system-events-service
    build:
      context: ./system-events-service
    image: docker-system-events-service
    environment:
      - JAVA_TOOL_OPTIONS=-XX:+TieredCompilation -XX:TieredStopAtLevel=1 -Xss256k
      - CONFIG_SERVER_URL=http://config-service:8888
      - EUREKA_SERVER_URL=http://eureka:8761/eureka
      - SS_DATABASE_URL=jdbc:mysql://db:3306/systemEventsServiceDB
    expose:
      - 8086
    depends_on:
      - configuration-service
      - eureka-service
      - db
    networks:
      - foodhaven
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 5

  user-service:
    container_name: user-service
    build:
      context: ./user-service
    image: docker-user-service
    environment:
      - JAVA_TOOL_OPTIONS=-XX:+TieredCompilation -XX:TieredStopAtLevel=1 -Xss256k
      - CONFIG_SERVER_URL=http://config-service:8888
      - EUREKA_SERVER_URL=http://eureka:8761/eureka
      - US_DATABASE_URL=jdbc:mysql://db:3306/userServiceDB
    expose:
      - 8083
    networks:
      - foodhaven
    depends_on:
      - configuration-service
      - eureka-service
      - db
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 5

  recipe-service:
    container_name: recipe-service
    build:
      context: ./recipe-service
    image: docker-recipe-service
    restart: always
    environment:
      - JAVA_TOOL_OPTIONS=-XX:+TieredCompilation -XX:TieredStopAtLevel=1 -Xss256k
      - CONFIG_SERVER_URL=http://config-service:8888
      - EUREKA_SERVER_URL=http://eureka:8761/eureka
      - RS_DATABASE_URL=jdbc:mysql://db:3306/recipeServiceDB
      - RABBITMQ_HOST=rabbitmq
    expose:
      - 8082
    networks:
      - foodhaven
    depends_on:
      - rabbitmq
      - configuration-service
      - eureka-service
      - db
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 5

  rating-service:
    container_name: rating-service
    build:
      context: ./rating-service
    image: docker-rating-service
    environment:
      - JAVA_TOOL_OPTIONS=-XX:+TieredCompilation -XX:TieredStopAtLevel=1 -Xss256k
      - CONFIG_SERVER_URL=http://config-service:8888
      - EUREKA_SERVER_URL=http://eureka:8761/eureka
      - RRS_DATABASE_URL=jdbc:mysql://db:3306/reviewServiceDB
      - RABBITMQ_HOST=rabbitmq
    expose:
      - 8081
    networks:
      - foodhaven
    depends_on:
      - rabbitmq
      - configuration-service
      - eureka-service
      - db
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 5

  ingredient-service:
    container_name: ingredient-service
    build:
      context: ./ingredient-service
    image: docker-ingredient-service
    environment:
      - JAVA_TOOL_OPTIONS=-XX:+TieredCompilation -XX:TieredStopAtLevel=1 -Xss256k
      - CONFIG_SERVER_URL=http://config-service:8888
      - EUREKA_SERVER_URL=http://eureka:8761/eureka
      - IS_DATABASE_URL=jdbc:mysql://db:3306/ingredientServiceDB
    expose:
      - 8084
    networks:
      - foodhaven
    depends_on:
      - configuration-service
      - eureka-service
      - db
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 5

  api-gateway:
    container_name: api-gateway
    hostname: api-gateway
    build:
      context: ./api-gateway
    image: docker-api-gateway
    restart: always
    environment:
      - JAVA_TOOL_OPTIONS=-XX:+TieredCompilation -XX:TieredStopAtLevel=1 -Xss256k
      - EUREKA_SERVER_URL=http://eureka:8761/eureka
    expose:
      - 8088
    depends_on:
      - rabbitmq
      - db
      - configuration-service
      - eureka-service
      - system-events-service
      - user-service
      - recipe-service
      - rating-service
      - ingredient-service
    networks:
      - foodhaven
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 5

  frontend:
    container_name: frontend
    build:
      context: ./frontend
    image: docker-frontend
    ports:
      - "3000:3000"
    depends_on:
      - api-gateway
    networks:
      - foodhaven
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 5

networks:
  foodhaven:
    driver: bridge