spring:
  # ovo za main je dodano kako bi se mogao pokrenuti servis
  main:
    web-application-type: reactive # dodaje asinhronost, extends WebSecurityConfigurerAdapter ne radi kada je ovdje reactive
    allow-bean-definition-overriding: true

  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: ingredient-service
          predicates:
            - Path=/api/ingredients/**
          uri: lb://ingredient-service
        - id: rating-service
          predicates:
            - Path=/api/ratings/**
          uri: lb://rating-service
        - id: recipe-service
          predicates:
            - Path=/api/recipes/**
          uri: lb://recipe-service
        - id: user-service
          uri: http://localhost:8083/
          predicates:
            - Path=/api/users/**
          #      todo riješiti ovaj problem: ne povlači sa Eureka servera iako bi moralo raditi!
          filters:
            - StripPrefix=1
        - id: auth-service
          uri: http://localhost:8083/
          predicates:
            - Path=/login/**
          filters:
            - StripPrefix=1
server:
  port: 8088

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true