spring:
#  # ovo za main je dodano kako bi se mogao pokrenuti servis
#  main:
#    web-application-type: reactive # dodaje asinhronost, extends WebSecurityConfigurerAdapter ne radi kada je ovdje reactive
#    allow-bean-definition-overriding: true

  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: ingredient-service
          predicates:
            - Path=/api/ingredients/**
          uri: lb://ingredient-service
        - id: rating-service
          predicates:
            - Path=/api/ratings/**
          uri: lb://rating-service
        - id: recipe-service
          predicates:
            - Path=/api/recipes/**
          uri: lb://recipe-service
        - id: user-service
          predicates:
            - Path=/api/users/**
          uri: lb://user-service
#          uri: http://localhost:8083/
          filters:
            - StripPrefix=1
        - id: auth-service
          predicates:
            - Path=/auth/**
          uri: lb://user-service
          filters:
            - StripPrefix=1
            - RemoveRequestHeader=Cookie
            - RemoveRequestHeader=Set-Cookie,Authorization
            - RemoveRequestHeader=Authorization     #Remove All the sensitive request headers (Cookie, Set-Cookie & Authorization) while passing request to downstream services

  security:
    user:
      password: "password"
server:
  port: 8088

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
