spring:
  application:
    name: api-gateway

server:
  port: 8088

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true

zuul:
  routes:
    ingredient-service:
      path: "/api/ingredients/**"
      serviceId: ingredient-service
      stripPrefix: false
    rating-service:
      path: "/api/ratings/**"
      serviceId: rating-service
      stripPrefix: false
    recipe-service:
      path: "/api/recipes/**"
      serviceId: recipe-service
      stripPrefix: false
    user-service:
      path: "/api/users/**"
#      todo riješiti ovaj problem: ne povlači sa Eureka servera iako bi moralo raditi!
#      serviceId: user-service
      serviceId: http://localhost:8083/
      stripPrefix: false

#    auth-service:
#      path: "/login/**"
##      serviceId: user-service
#      serviceId: http://localhost:8083/
#      stripPrefix: false
##      sensitive-headers: Cookie,Set-Cookie

    token:
      path: "/oauth/token/**"
#      serviceId: user-service
      serviceId: http://localhost:8083/
      stripPrefix: false
  sensitive-headers: